name: Build and Deploy Main
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Build and deploy to Github Pages
    uses: ./.github/workflows/deploy.yml
    secrets:
      gh_pages_token: ${{ secrets.GH_PAGES_TOKEN }}
    