name: Prettier and Build Check

on: workflow_call

jobs:
  prettify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write src/**/*.{js,jsx,ts,tsx}
          commit_message: Prettify code
